doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        # SQLite specific configuration
        driver: 'pdo_sqlite'
        charset: 'utf8mb4'
        default_table_options:
            charset: 'utf8mb4'
            collate: 'utf8mb4_unicode_ci'
    orm:
        auto_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
